### PR TITLE
Customize activitybar

### PR DESCRIPTION
**Pull request by dtrucs**
- [x] Tickets : 
  - [Pouvoir grouper les types par catégorie sur la HOME (événements touristiques et autres) #560](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/560)
  - [Pouvoir paramétrer le nombre d'éléments affichés sur la page d'accueil #568 ](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/568)
- [x] I made sure that all displayed texts are imported from translation files.

### CODE REVIEW

**Comment by babastienne** [comment]
Is it possible to improve the documentation ? I have the feeling that the documentation is minimalist in camparison with [this comment](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/560#issuecomment-1858166341) that is way more detailed. At least add a link in the documentation to referecne the comment in order to not "loose" this knowledge.

What do you think @bruhnild ?

**Comment by bruhnild** [comment]
> Is it possible to improve the documentation ? I have the feeling that the documentation is minimalist in camparison with [this comment](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/560#issuecomment-1858166341) that is way more detailed. At least add a link in the documentation to referecne the comment in order to not "loose" this knowledge.
> 
> What do you think @bruhnild ?

I agree, this comment is very clear and detailed and deserves to be included in the [documentation](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md) to explain how the new variables in the [home.json](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/home.json) file work

**Review by babastienne — CHANGES_REQUESTED** [review]
Improve documentation (see comments above)

**Comment by dtrucs** [comment]
> Improve documentation (see comments above)

Added :+1:

**Review by Bo-Duke — APPROVED** [review]

**Review by babastienne — APPROVED** [review]

**Pull request merged**
